---
name: Check

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  check_project:
    name: Check (${{ matrix.pg_version.name }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pg_version:
          - { shell: "pg16", name: "PG 16" }
          - { shell: "pg17", name: "PG 17" }
          - { shell: "pg18", name: "PG 18" }
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Init Nix environment
        run:
          nix develop .#${{ matrix.pg_version.shell }} --command -- echo "Done"
      - name: Run Commit checks
        if: matrix.pg_version.shell == 'pg16'
        run: |
          nix develop .#${{ matrix.pg_version.shell }} --command -- pre-commit run --all-files --color always
      - name: Create local postgres installation
        run: |
          sudo chown "$USER" /run/postgresql
          nix develop .#${{ matrix.pg_version.shell }} --command -- ./ci/setup.sh
      - name: Build and run tests
        run: |
          nix develop .#${{ matrix.pg_version.shell }} --command -- ./ci/run.sh
